{{- if not .Values.config.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prox-api-gateway.fullname" . }}
  labels:
    {{- include "prox-api-gateway.labels" . | nindent 4 }}
data:
  application.yml: |-
    spring:
      application:
        name: api-gateway
      cloud:
        gateway:
          x-forwarded:
            port-enabled: false
            host-enabled: false
            proto-enabled: false
            port-append: false
            host-append: false
            proto-append: false
            enabled: false
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowedMethods: "*"
                allowedHeaders: "*"
          routes:
            - id: project-service
              uri: http://prox-project-service.prox.svc.cluster.local:8080
              predicates:
                - Path=/projects/**,/moduleTypes/**,/studyPrograms/**
              metadata:
                openApiPath: "/v3/api-docs"
            - id: tag-service
              uri: http://prox-tag-service.prox.svc.cluster.local:8080
              predicates:
                - Path=/tags/**,/tagCollections/**,/tagRecommendations/**
              metadata:
                openApiPath: "/v3/api-docs"
            - id: professor-profile-service
              uri: http://prox-professor-profile-service.prox.svc.cluster.local:8080
              predicates:
                - Path=/faculties/**,/professors/**
              metadata:
                openApiPath: "/v3/api-docs"
            - id: company-profile-service
              uri: http://prox-company-profile-service.prox.svc.cluster.local:8080
              predicates:
                - Path=/companies/**,/languages/**
              metadata:
                openApiPath: "/v3/api-docs"
            - id: job-service
              uri: http://prox-job-service.prox.svc.cluster.local:8080
              predicates:
                - Path=/jobOffers/**,/jobOfferTypes/**,/jobOfferEntryLevels/**
              metadata:
                openApiPath: "/v3/api-docs"
            - id: user-service
              uri: http://prox-user-service.prox.svc.cluster.local:8080
              predicates:
                - Path=/users/**,/organizations/**
              metadata:
                openApiPath: "/q/openapi"
    springdoc:
      swagger-ui:
        urls: # Do not remove! Workaround to set swagger ui urls programmatically
{{- end }}
